#!/bin/bash

if [ -z "$JAVA_HOME" ]; then
  echo "empty JAVA_HOME" 1>&2
  exit 1
fi

java -cp build/libs/jccdump-1.0.jar:$JAVA_HOME/lib/sa-jdi.jar:$JAVA_HOME/lib/tools.jar com.github.buzztaiki.jccdump.Main "$@"
